export let postCardsArray = [
    {id:1,
    img:"../images/cards/card1.webp"
    },
     {id:2,
    img:"../images/cards/card2.webp"
    },
     {id:3,
    img:"../images/cards/card3.webp"
    },
     {id:4,
    img:"../images/cards/card4.webp"
    },
     {id:5,
    img:"../images/cards/card5.webp"
    },
     {id:6,
    img:"../images/cards/card6.webp"
    },
     {id:7,
    img:"../images/cards/card7.webp"
    },
     {id:8,
    img:"../images/cards/card8.webp"
    },
     {id:9,
    img:"../images/cards/card9.webp"
    },
     {id:10,
    img:"../images/cards/card10.webp"
    },
        {id:11,
    img:"../images/cards/card11.webp"
    },
     {id:12,
    img:"../images/cards/card12.webp"
    },
     {id:13,
    img:"../images/cards/card13.webp"
    },
     {id:14,
    img:"../images/cards/card14.webp"
    },
     {id:15,
    img:"../images/cards/card15.webp"
    },
     {id:16,
    img:"../images/cards/card16.webp"
    },
     {id:17,
    img:"../images/cards/card17.webp"
    },
     {id:18,
    img:"../images/cards/card18.webp"
    },
     {id:19,
    img:"../images/cards/card19.webp"
    },
     {id:20,
    img:"../images/cards/card20.webp"
    },
     {id:21,
    img:"../images/cards/card21.webp"
    },
        {id:22,
    img:"../images/cards/card22.webp"
    },
     {id:23,
    img:"../images/cards/card23.webp"
    },
     {id:24,
    img:"../images/cards/card24.webp"
    },
     {id:25,
    img:"../images/cards/card25.webp"
    },
     {id:26,
    img:"../images/cards/card26.webp"
    },
     {id:27,
    img:"../images/cards/card27.webp"
    },
     {id:28,
    img:"../images/cards/card28.webp"
    },
     {id:29,
    img:"../images/cards/card29.webp"
    },
     {id:30,
    img:"../images/cards/card30.webp"
    },
    {id:31,
    img:"../images/cards/modelCard.webp"
    }
]