export let post_cards_array = [
    {id:1,
    img:".././images/cards/card1.jpeg"
    },
     {id:2,
    img:".././images/cards/card2.jpeg"
    },
     {id:3,
    img:".././images/cards/card3.jpeg"
    },
     {id:4,
    img:".././images/cards/card4.jpeg"
    },
     {id:5,
    img:".././images/cards/card5.jpeg"
    },
     {id:6,
    img:".././images/cards/card6.jpeg"
    },
     {id:7,
    img:".././images/cards/card7.jpeg"
    },
     {id:8,
    img:".././images/cards/card8.jpeg"
    },
     {id:9,
    img:".././images/cards/card9.jpeg"
    },
     {id:10,
    img:".././images/cards/card10.jpeg"
    },
        {id:11,
    img:".././images/cards/card11.jpeg"
    },
     {id:12,
    img:".././images/cards/card12.jpeg"
    },
     {id:13,
    img:".././images/cards/card13.jpeg"
    },
     {id:14,
    img:".././images/cards/card14.jpeg"
    },
     {id:15,
    img:".././images/cards/card15.jpeg"
    },
     {id:16,
    img:".././images/cards/card16.jpeg"
    },
     {id:17,
    img:".././images/cards/card17.jpeg"
    },
     {id:18,
    img:".././images/cards/card18.jpeg"
    },
     {id:19,
    img:".././images/cards/card19.jpeg"
    },
     {id:20,
    img:".././images/cards/card20.jpeg"
    }

]