export let postCardsArray = [
    {id:1,
    img:".././images/cards/card1.png"
    },
     {id:2,
    img:".././images/cards/card2.png"
    },
     {id:3,
    img:".././images/cards/card3.png"
    },
     {id:4,
    img:".././images/cards/card4.png"
    },
     {id:5,
    img:".././images/cards/card5.png"
    },
     {id:6,
    img:".././images/cards/card6.png"
    },
     {id:7,
    img:".././images/cards/card7.png"
    },
     {id:8,
    img:".././images/cards/card8.png"
    },
     {id:9,
    img:".././images/cards/card9.png"
    },
     {id:10,
    img:".././images/cards/card10.png"
    },
        {id:11,
    img:".././images/cards/card11.jpeg"
    },
     {id:12,
    img:".././images/cards/card12.jpeg"
    },
     {id:13,
    img:".././images/cards/card13.jpeg"
    },
     {id:14,
    img:".././images/cards/card14.jpeg"
    },
     {id:15,
    img:".././images/cards/card15.jpeg"
    },
     {id:16,
    img:".././images/cards/card16.jpeg"
    },
     {id:17,
    img:".././images/cards/card17.jpeg"
    },
     {id:18,
    img:".././images/cards/card18.jpeg"
    },
     {id:19,
    img:".././images/cards/card19.jpeg"
    },
     {id:20,
    img:".././images/cards/card20.jpeg"
    },
     {id:21,
    img:".././images/cards/card21.jpeg"
    },
        {id:22,
    img:".././images/cards/card22.jpeg"
    },
     {id:23,
    img:".././images/cards/card23.jpeg"
    },
     {id:24,
    img:".././images/cards/card24.jpeg"
    },
     {id:25,
    img:".././images/cards/card25.jpeg"
    },
     {id:26,
    img:".././images/cards/card26.jpeg"
    },
     {id:27,
    img:".././images/cards/card27.jpeg"
    },
     {id:28,
    img:".././images/cards/card28.jpeg"
    },
     {id:29,
    img:".././images/cards/card29.jpeg"
    },
     {id:30,
    img:".././images/cards/card30.jpeg"
    }
]